### ISSUE TITLE
seq_number for async messages

### ISSUE THREAD

**Issue by Critically** [uudashr/jsmpp#15]
I need to send messages asynchronous, but i need to know seq_number of messages what i send, then i must to compare this seq_numbers and get message_id for message

2.1.0 Fedora

**Comment by uudashr** [comment]
Jsmpp will ensure the returned message id from sumitShortMessage are valid.
Use thread pool to get more messages/sec. Internally jsmpp already use
asynchronous, but end user (programmer) use as simple as synchronous way.

**Comment by Critically** [comment]
I use the code from your example SubmitMultipartMultilangualExample.java and to send more messages per second, I have to do something like this?

/ / Submit all messages
for (int i = 0; i <byteMessagesArray.length; i + +) {
execService.execute (new Runnable () {
            public void run () {
String messageId = submitMessage (session, byteMessagesArray [i], sourceMsisdn, destinationMsisdn,
messageClass, alphabet, esmClass);
System.out.println ("Message submitted, message_id is" + messageId);
                 }
          });
}

With Tranceiver it will be work ?

**Comment by uudashr** [comment]
Correct

**Comment by Critically** [comment]
Thanks, i'm trying this today....
