### ISSUE TITLE
Two sessions

### ISSUE THREAD

**Issue by Critically** [uudashr/jsmpp#17]
Hello, my question is: If i do two sessions with binding two TRX they work sync or async ?

**Comment by uudashr** [comment]
Jsmpp works async, but user able to use it as sync. If you submit the
message on thread pool then you will get the advantages of async.
TRX, RX, TX are just the same.

**Comment by Critically** [comment]
Thank you...

**Comment by Critically** [comment]
266 [pool-1-thread-1] DEBUG org.jsmpp.session.AbstractSessionContext  - Activity notified
266 [pool-1-thread-1] DEBUG org.jsmpp.session.state.SMPPSessionOpen  - Bind Response header (29, 80000009, 00000000, 1)
267 [AWT-EventQueue-0] DEBUG org.jsmpp.session.AbstractSession  - bind response received
268 [Thread-5] INFO org.jsmpp.session.SMPPSession  - Starting EnquireLinkSender
270 [AWT-EventQueue-0] DEBUG org.jsmpp.session.SMPPSession  - Connect and bind to server2.smstraffic.ru port 4442
270 [AWT-EventQueue-0] DEBUG org.jsmpp.session.SMPPSession  - Connect and bind to server2.smstraffic.ru port 4442
330 [pool-1-thread-2] DEBUG org.jsmpp.session.AbstractSessionContext  - Activity notified
330 [pool-1-thread-2] DEBUG org.jsmpp.session.AbstractSessionContext  - Activity notified
330 [pool-1-thread-2] DEBUG org.jsmpp.session.SMPPSession  - Sending enquire_link_resp
330 [pool-1-thread-2] DEBUG org.jsmpp.session.SMPPSession  - Sending enquire_link_resp
356 [AWT-EventQueue-0] INFO org.jsmpp.session.SMPPSession  - Connected
356 [AWT-EventQueue-0] INFO org.jsmpp.session.SMPPSession  - Connected
356 [Thread-6] INFO org.jsmpp.session.SMPPSession  - Starting PDUReaderWorker with processor degree:3 ...
356 [Thread-6] INFO org.jsmpp.session.SMPPSession  - Starting PDUReaderWorker with processor degree:3 ...

As u see if i do 2 session, they working in u pool but in one thread..... And then when i starts to send message to them from 2 threads with it's own pool, they work sync... So at first work 1-thread then 2-thread... It is possible to do session, in one pool but in different threads ???

P.S. - sorry for bad english...
