### ISSUE TITLE
Async speed is not more 20sms/s, why ?

### ISSUE THREAD

**Issue by Critically** [uudashr/jsmpp#18]
If I run one session and retrieve an admissible 40sms of MYSQL, then the program will still send up to 20 SMS per second, that's the last time I look at the magazine where it SMSC 21sms/s then 14sms/s then 5sms/s

And I send sms ,as u told me, with ExecutorService like:

execService = Executors.newFixedThreadPool(20);

for (int j = 0; j < byteMessagesArray.length; j++) {
Future<?> future = execService.submit(new MyRunnable (j, byteMessagesArray, hashtable, id, sourceMsisdn, destinationMsisdn, messageClass, alphabet, esmClass, z) {});
list.add(future);
}

**Comment by uudashr** [comment]
Bottleneck issue can be on your DBMS access, your code, network latency and
SMSC response time.

Ask the telco provideer about the SMSC average &  max response time
