### ISSUE TITLE
Reconnect to SMSC with Transmitter and Receiver

### ISSUE THREAD

**Issue by Critically** [uudashr/jsmpp#19]
I create Reconnect thread, that check connection, and if it lose, reconnect to SMSC

public static void ConnectToSMSCtx() throws NumberFormatException, IOException
{ 
        BasicConfigurator.configure();
        String dt = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(java.util.Calendar.getInstance ().getTime());
        session = new SMPPSession();
        try {
             session.connectAndBind(Constants.SMPP_HOST, Integer.parseInt(Constants.SMPP_PORT), new BindParameter(BindType.BIND_TX, Constants.SMPP_LOGIN, Constants.SMPP_PASSWORD, null,TypeOfNumber.ALPHANUMERIC,NumberingPlanIndicator.ISDN, null));
        } catch (IOException e2) {
            ta.append("Failed connect and bind to host -> "+dt+"\n");
            e2.printStackTrace();
            }
           if (session.getSessionState().isBound()){
            ta.append("Connected to SMSC with Transmitter itakazan3:str7 -> "+dt+ "\n");
            dt=null;
           }
}

Then my thread check connection:

public void run(){
    while (isActive){  
    try {
        sleep(1000);

```
while (MainForm.session == null || MainForm.session.getSessionState().equals(SessionState.CLOSED)){
    MainForm.Thread1.MySuspend();
    sleep(2000);
    MainForm.ConnectToSMSCtx();
    if (MainForm.session.getSessionState().isBound()){
        MainForm.Thread1.MyResume();    
    }
}
```

  while (MainForm.session2 == null || MainForm.session2.getSessionState().equals(SessionState.CLOSED)){
        sleep(2000);
        MainForm.ConnectToSMSCrx();
    }

```
} catch (InterruptedException e) {} 
  catch (NumberFormatException e) {} 
  catch (IOException e) {}      
```

}  
}

but when it reconnect... I see this:
2944056 [AWT-EventQueue-0] DEBUG org.jsmpp.session.AbstractSession  - unbind response received
2944056 [AWT-EventQueue-0] DEBUG org.jsmpp.session.AbstractSession  - unbind response received
2944056 [AWT-EventQueue-0] DEBUG org.jsmpp.session.AbstractSession  - unbind response received
2944056 [AWT-EventQueue-0] DEBUG org.jsmpp.session.AbstractSession  - unbind response received
2944056 [AWT-EventQueue-0] DEBUG org.jsmpp.session.AbstractSession  - unbind response received
2944056 [AWT-EventQueue-0] DEBUG org.jsmpp.session.AbstractSession  - unbind response received
2944057 [Thread-10] INFO org.jsmpp.session.SMPPSession  - PDUReaderWorker stop
2944057 [Thread-10] INFO org.jsmpp.session.SMPPSession  - PDUReaderWorker stop
2944057 [Thread-10] INFO org.jsmpp.session.SMPPSession  - PDUReaderWorker stop
2944057 [Thread-10] INFO org.jsmpp.session.SMPPSession  - PDUReaderWorker stop
2944057 [Thread-10] INFO org.jsmpp.session.SMPPSession  - PDUReaderWorker stop
2944057 [Thread-10] INFO org.jsmpp.session.SMPPSession  - PDUReaderWorker stop
2944236 [Thread-11] INFO org.jsmpp.session.SMPPSession  - EnquireLinkSender stop
2944236 [Thread-11] INFO org.jsmpp.session.SMPPSession  - EnquireLinkSender stop
2944236 [Thread-11] INFO org.jsmpp.session.SMPPSession  - EnquireLinkSender stop
2944236 [Thread-11] INFO org.jsmpp.session.SMPPSession  - EnquireLinkSender stop
2944236 [Thread-11] INFO org.jsmpp.session.SMPPSession  - EnquireLinkSender stop
2944236 [Thread-11] INFO org.jsmpp.session.SMPPSession  - EnquireLinkSender stop
2944955 [Thread-13] INFO org.jsmpp.session.SMPPSession  - EnquireLinkSender stop
2944955 [Thread-13] INFO org.jsmpp.session.SMPPSession  - EnquireLinkSender stop
2944955 [Thread-13] INFO org.jsmpp.session.SMPPSession  - EnquireLinkSender stop
2944955 [Thread-13] INFO org.jsmpp.session.SMPPSession  - EnquireLinkSender stop
2944955 [Thread-13] INFO org.jsmpp.session.SMPPSession  - EnquireLinkSender stop
2944955 [Thread-13] INFO org.jsmpp.session.SMPPSession  - EnquireLinkSender stop

I think it's not good, can u say me please how to solve my problem ? Or it's good ?

**Comment by Critically** [comment]
Can u help me please ?

**Comment by uudashr** [comment]
Make sure you create new session instance. Do not invoke connect more than
one on the same session.
