### ISSUE TITLE
Response Timeout

### ISSUE THREAD

**Issue by Critically** [uudashr/jsmpp#21]
Dear, uudashr can u help me again please.. I bind with TX, then i start to send messages, any messages sends good, but sometimes as u can see, I have "Response timeout" error. What does this error mean ? And how  to solve my problem ?

60529 [pool-71309-thread-43] DEBUG org.jsmpp.session.AbstractSession  - submit_sm response received
60529 [pool-71309-thread-39] DEBUG org.jsmpp.session.AbstractSession  - submit_sm response received
60597 [pool-3-thread-1] DEBUG org.jsmpp.session.AbstractSessionContext  - Activity notified
60598 [pool-71309-thread-41] DEBUG org.jsmpp.session.AbstractSession  - submit_sm response received
60597 [pool-3-thread-2] DEBUG org.jsmpp.session.AbstractSessionContext  - Activity notified
60598 [pool-71309-thread-40] DEBUG org.jsmpp.session.AbstractSession  - submit_sm response received
Response timeout
Response timeout
Response timeout
Response timeout

**Comment by Critically** [comment]
Please help me...

**Comment by uudashr** [comment]
It means there is no response receice from server after specific interval.

**Comment by Critically** [comment]
Thanks, and why i take this error ? It's problem in my code, or it's problem in SMSC ?

**Comment by uudashr** [comment]
Not sure. Possible on the SMSC.
It would be better you use wireshark to analyze the SMPP packet. Is it
really time out.

Regards,

**Comment by Critically** [comment]
Dear uudashr, I'm trying to do Session.SetTransactionInterval(5000L), but sometimes i take this error "Response timeout". Can you recommend me something ? I'm using jsmpp 2.1.0

**Comment by muellerc** [comment]
As Nuruddin already wrote, your SMSC probably doesn't respond with the time limit. I recommend to "whireshark" your connection and check whether this is the case.
I'm not sure what do you expect the JSMPP library should do in this case?

**Comment by Critically** [comment]
I have already used "WireShark", and I see that, I have not come with packages response. What do I do in this case?

**Comment by muellerc** [comment]
I propose to contact your SMSC provider and ask why they do not respond
with the time limit.

Best,

## Christian

Software Integration Specialist

Apache Camel committer: https://camel.apache.org/team
V.P. Apache Camel: https://www.apache.org/foundation/
Apache Member: https://www.apache.org/foundation/members.html

https://www.linkedin.com/pub/christian-mueller/11/551/642

**Comment by Critically** [comment]
Hm, and if SMSC say me that, they send me response ?

**Comment by muellerc** [comment]
Within the time limit? Can you increase it?

Best,
Christian
Am 17.09.2013 09:03 schrieb "Critically" notifications@github.com:

**Comment by Critically** [comment]
They say, that limit can be <1s

**Comment by muellerc** [comment]
I don't know how I can further help. If you do not receive the response
from your SMSC within the configured timeout, it's expected to see this log
entry.
You have to check your connection to the SMSC whether they send the
response or not.

Best,

## Christian

Software Integration Specialist

Apache Camel committer: https://camel.apache.org/team
V.P. Apache Camel: https://www.apache.org/foundation/
Apache Member: https://www.apache.org/foundation/members.html

https://www.linkedin.com/pub/christian-mueller/11/551/642

**Comment by uudashr** [comment]
WireShark capture the network packet. If you never see the response then
there is no response from SMSC come to your machine.
If this occured, you have to make sure tge SMSC already send the response
correctly. If SMSC works fine, then there might be network configuration
issue.

**Comment by mohannara** [comment]
I'm also facing same issue. But According to the WireShark I have received submit_sm - resp within mili sconds. What would be the case? In the log below is recording. But this is coming when load is high. I have implemented throttling mechanism (30/sec). But issue still exists.

2014-05-05 15:40:41,201 ERROR [CEP_LOGGER](pool-22-thread-2) 777335343:: SMS delivery failed due to No response after waiting for 5000 millis when executing submit_sm with sessionId cf29675c and sequenceNumber 576

jsmpp version - 2.1.0
