### ISSUE TITLE
Enquire Link heart beat

### ISSUE THREAD

**Issue by ADTC** [uudashr/jsmpp#30]
I understand that the jsmpp hides away the dirty details of the SMPP implementation (and I admit, it's really dirty!)

However, my client keeps requesting that the heartbeat (enquire link) should be set to < 50 sec even though I keep insisting that there's no such setting in "the API we are using" (jsmpp). I want to know:
1. What the default enquire_link timeout period in jsmpp? (If possible, please point to the code where this is defined.)
2. Is it possible to change it during runtime (without re-compiling the API)?

**Comment by AndrewBourgeois** [comment]
1. 5000 millisecond, defined in `org.jsmpp.session.AbstractSession`
2. Yes and No. There's a `setEnquireLinkTimer` method on both `SMPPSession` and `SMPPServerSession` but it only works for the `SMPPSession` one. Setting it on the `SMPPServerSession` has no effect (=bug) and you'll still have an `enquire_link` every 5000 milliseconds.

I'll open up an issue for this as I'm currently struggling with this (which also explains why I still reply to an old discussion).

**Comment by ADTC** [comment]
This was so long ago. Thank you for the clarifications. I saw your issue #35 and I support you :)

`BTW` you can use ` marks for `code markdown` :)
