### ISSUE TITLE
SMS sent via JSMPP not saved on a phone - “push” only

### ISSUE THREAD

**Issue by 14v** [uudashr/jsmpp#37]
I'm sending SMS via JSMPP as described in SubmitMultipartMultilangualExample.java. Current SMS is with latin symbols only and does not overlap 160 chars limit - no multipart message is sent, single one only.

So on mobile phone I see only push notification with Cancel and Save buttons (Android) or simply open message on my old Sony Ericsson. Text is delivered correctly, but message does not appear in "incoming" folder! 

How to send ordinary SMS with no "hacks"?

Theres also question on stackoverflow http://stackoverflow.com/questions/26340090/sms-sent-via-jsmpp-not-saved-on-a-phone-push-only

**Comment by 14v** [comment]
Changed MessageClass.CLASS0 to MessageClass.CLASS1 at `GeneralDataCoding`'s constructor parameter and it's gone. 

I'm using 2.1.0_4 artifact from http://mvnrepository.com/artifact/org.apache.servicemix.bundles/org.apache.servicemix.bundles.jsmpp and there's only `GeneralDataCoding(boolean compressed, boolean containMessageClass, MessageClass messageClass, Alphabet alphabet)` constructor with alphabet available.

Can anybody comment this situation? Is it a solution to get newer version?

**Comment by ADTC** [comment]
Class 0 is ["Flash SMS"](https://en.wikipedia.org/wiki/Short_Message_Service#Flash_SMS) which is for single-use alert messages, while Class 1 is regular SMS which is stored in the Inbox for future retrieval.

The different classes are described [at this page](http://www.sms-wiki.org/p_28-flash-sms.html).

> Flash SMS is an SMS message which is displayed on the phone screen immediately upon arrival. [...] Flash SMS can be a handy alternative to standard SMS messages when you want to catch the attention of the recipient(s) immediately. [...] Flash SMS message is a class 0 message, which means that it is classified as most important. 
> 
> **Class 0:** This message is displayed on the mobile phone immediately and a message delivery report is sent back to the SC. The message does not have to be saved in the mobile phone or on the SIM card (unless selected to do so by the mobile user). This type is also referred to as Flash SMS.
> 
> **Class 1 SMS:** This message is stored in the memory of the mobile phone or the SIM card (depending on memory availability).
> 
> **Class 2 SMS:** This message class is Phase 2-specific and carries SIM card data. The SIM card data must be successfully transferred prior to sending acknowledgment to the SC. An error message is sent to the SC if this transmission is not possible.
> 
> **Class 3 SMS:** This message is forwarded from the receiving entity to an external device. The delivery acknowledgment is sent to the SC regardless of whether or not the message was forwarded to the external device.

**Comment by 14v** [comment]
Further testing gives that it's safer to use `new GeneralDataCoding(alphabet.value())` constructor for data coding because some SMPP providers do not understand compression and class bytes and send 'null' as text instead of message. `alphabet` is `Alphabet.ALPHA_UCS2` (0x08) for multilingual (Unicode) messages and `Alphabet.ALPHA_DEFAULT` (0x00) for latin. That sends ordinary SMS because it is used to be a default choise.
